### ISSUE TITLE
Infinite Loading of SPDX documents in the SBOM tab of the pipeline

### ISSUE THREAD

**Issue by SESEric** [rhyskoedijk/sbom-azure-devops#6]
Hi,

once the pipeline is complete, when i click on the SBOM tab i get an infinite loading of the SPDX document:
![image](https://github.com/user-attachments/assets/d18c54b8-20fa-4bf9-8101-bbc98fdace91)

The files does seems properly generated as i am able to access them

**Comment by rhyskoedijk** [comment]
@SESEric are there any [relevant] JavaScript errors in the web developer console? On the network tab of the developer console, there should be a request to `manifest.spdx.json` and `manifest.spdx.svg` (if the "graph" option was enabled), what were the results of these requests?

![image](https://github.com/user-attachments/assets/7005a81b-93a1-424f-a0b9-2a3de5d51d29)

**Comment by SESEric** [comment]
Yes indeed there is an issue with the version used for the azure rest API. we are still using an older azure devops server (6.1)
![image](https://github.com/user-attachments/assets/899dc6ad-c76b-47b0-9e1c-35857e63b91f)

**Comment by SESEric** [comment]
@rhyskoedijk that's awesome. Great extension by the way, was about to code those feature out.

By the way, how do you generate the XLSX? could see an option for it.

**Comment by rhyskoedijk** [comment]
> By the way, how do you generate the XLSX? couldnt see an option for it.

Currently it can only be exported from the SBOM tab but I do plan on making it a task option similar to the SVG option so that it can be saved directly to the published artifacts.

![image](https://github.com/user-attachments/assets/407e7718-2b77-4e65-bf7c-a52f4d11846a)

I hope to get a few improvements out (including better exporting) over the next week or two.

**Comment by rhyskoedijk** [comment]
@SESEric minimum server API version has been lowered to 5.0; hopefully that works for your server now.

**Comment by SESEric** [comment]
works well. Thanks!

**Comment by rhyskoedijk** [comment]
> By the way, how do you generate the XLSX? couldnt see an option for it.

Starting from v1.3.0, the XLSX spreadsheet can now be generated from the pipeline task by setting
`enableManifestSpreadsheetGeneration: true`
